services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - mynetwork

  goapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-couchdb
    ports:
      - "8080:8080"
    environment:
      COUCHDB_URL: http://admin:password@couchdb:5984
    depends_on:
      - couchdb
    networks:
      - mynetwork
    
networks:
  mynetwork:
    driver: bridge

volumes:
  couchdb_data:
  